const projects = [
    {
        id: 1,
        title: "Gastropub Lamyata",
        category: "branding",
        thumbnail: "./pictures/lamyata-thumbnail.jpg",
        fullImage: "./pictures/lamyata-full.jpg",
        resolutionPx: "7633x2186px",
        resolutionPpi: "150ppi",
        fileName: "branding_lamyata.psd",
        fileSize: "5.2MB",
        overview: "Lamyata (Bulgarian for “The Dragon”) is a modern gastropub that celebrates bold flavors, fire-grilled dishes, and a gritty urban vibe. The goal of this project was to create a cohesive brand identity that embodies the raw energy of flame-cooked food while appealing to a digitally connected, social-media-driven audience.",
        conceptVisualLanguage: "The core concept revolves around the slavic folklore presented in a modern way. A custom logomark features a stylized “Lamya” for the top and transforms into burger, symbolizing both the name and the food style. The color palette—dominated by deep reds, black, and charred textures—evokes fire, smoke, and rich, grilled flavor.",
        deliverablesIncluded: "<ul><li>Logo & Visual Identity</li><li>Custom Beer Bottle Labels (names like “Fire,” “Charcoal,” “Smoke”)</li><li>Takeout Packaging (containers, wraps, bags, cups)</li><li>Interior Visual Elements (neon signage, overall concept)</li><li>Print Collateral (menus, brochures, flyers)</li><li>Advertising Campaign</li><li>Tagline: *“Храна за [С]пoделяне” (“Food for Sharing/[Scrolling]”)</li><li>Social Media-inspired poster series</li><li>Vehicle Graphics for branded delivery</li><li>Social Media Visuals in multiple formats</li></ul>",
        technologies: ["Photoshop", "Illustrator"],
    },
    {
        id: 2,
        title: "E-commerce Website Mockup",
        category: "web",
        thumbnail: "https://i.imgur.com/rY9JvYp.png",
        fullImage: "https://i.imgur.com/rY9JvYp.png",
        resolutionPx: "1366x768px",
        resolutionPpi: "72ppi",
        fileName: "ecommerce_homepage.psd",
        fileSize: "22.8MB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["Photoshop", "Figma"],
        link: ""
    },
    {
        id: 3,
        title: "Indie Film Festival Poster",
        category: "posters",
        thumbnail: "https://i.imgur.com/aT3bA4j.png",
        fullImage: "https://i.imgur.com/aT3bA4j.png",
        resolutionPx: "27x40 inches",
        resolutionPpi: "300ppi",
        fileName: "film_fest_poster_final.psd",
        fileSize: "85.1MB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["Photoshop"],
        link: "https://www.behance.net/gallery/123456789/Indie-Film-Festival-Poster"
    },
    {
        id: 4,
        title: "Sci-Fi Book Cover",
        category: "covers",
        thumbnail: "https://i.imgur.com/cM8J2aE.png",
        fullImage: "https://i.imgur.com/cM8J2aE.png",
        resolutionPx: "6x9 inches",
        resolutionPpi: "300ppi",
        fileName: "book_cover_art.psd",
        fileSize: "50.3MB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["Photoshop", "Wacom Tablet"],
        link: ""
    },
    {
        id: 6,
        title: "Product Photography Retouching",
        category: "social",
        thumbnail: "https://i.imgur.com/dG8fJ7s.png",
        fullImage: "https://i.imgur.com/dG8fJ7s.png",
        resolutionPx: "4000x6000px",
        resolutionPpi: "300ppi",
        fileName: "watch_retouch.psd",
        fileSize: "120.5MB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["Photoshop"],
        link: ""
    },
    {
        id: 7,
        title: "Coffee Shop Logo",
        category: "branding",
        thumbnail: "https://i.imgur.com/bV3O4Qz.png",
        fullImage: "https://i.imgur.com/bV3O4Qz.png",
        resolutionPx: "Vector",
        resolutionPpi: "N/A",
        fileName: "coffee_logo.ai",
        fileSize: "2.1MB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["Illustrator"],
        link: "https://www.behance.net/gallery/123456789/Coffee-Shop-Logo"
    },
    {
        id: 8,
        title: "Travel Blog UI/UX",
        category: "web",
        thumbnail: "https://i.imgur.com/xH6kE9w.png",
        fullImage: "https://i.imgur.com/xH6kE9w.png",
        resolutionPx: "1440x900px",
        resolutionPpi: "72ppi",
        fileName: "travel_blog_ui.xd",
        fileSize: "18.4MB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["Adobe XD", "Photoshop"],
        link: ""
    },
    {
        id: 9,
        title: "Music Concert Poster",
        category: "posters",
        thumbnail: "https://i.imgur.com/fI7mN8m.png",
        fullImage: "https://i.imgur.com/fI7mN8m.png",
        resolutionPx: "18x24 inches",
        resolutionPpi: "300ppi",
        fileName: "concert_poster.psd",
        fileSize: "63.7MB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["Photoshop"],
        link: "https://www.behance.net/gallery/123456789/Music-Concert-Poster"
    },
    {
        id: 11,
        title: "Corporate Video Graphics",
        category: "social",
        thumbnail: "https://i.imgur.com/jR8oV9y.png",
        fullImage: "https://i.imgur.com/jR8oV9y.png",
        resolutionPx: "1920x1080px",
        resolutionPpi: "72ppi",
        fileName: "corp_video_assets.aep",
        fileSize: "1.2GB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["After Effects", "Illustrator"],
        link: ""
    },
    {
        id: 12,
        title: "Fashion Photography Editing",
        category: "social",
        thumbnail: "https://i.imgur.com/mN7tB8p.png",
        fullImage: "https://i.imgur.com/mN7tB8p.png",
        resolutionPx: "3500x5250px",
        resolutionPpi: "300ppi",
        fileName: "fashion_edit.psd",
        fileSize: "150.0MB",
        overview: "",
        conceptVisualLanguage: "",
        deliverablesIncluded: "",
        technologies: ["Photoshop", "Capture One"],
        link: "https://www.behance.net/gallery/123456789/Fashion-Editorial"
    }
];