const projects = [
    {
        id: 1,
        title: "Gastropub “Lamyata”",
        category: "Branding",
        thumbnail: "./pictures/lamyata-thumbnail.jpg",
        fullImage: "./pictures/lamyata-full.jpg",
        resolutionPx: "7633x2186px",
        resolutionPpi: "150ppi",
        fileName: "branding_lamyata.psd",
        fileSize: "5.2MB",
        overview: "Lamyata (Bulgarian for “The Dragon”) is a modern gastropub that celebrates bold flavors, fire-grilled dishes, and a gritty urban vibe. The goal of this project was to create a cohesive brand identity that embodies the raw energy of flame-cooked food while appealing to a digitally connected, social-media-driven audience.",
        conceptVisualLanguage: "The core concept revolves around the slavic folklore presented in a modern way. A custom logomark features a stylized “Lamya” for the top and transforms into burger, symbolizing both the name and the food style. The color palette—dominated by deep reds, black, and charred textures—evokes fire, smoke, and rich, grilled flavor.",
        deliverablesIncluded: "<ul><li>Logo & Visual Identity</li><li>Custom Beer Bottle Labels (names like “Fire,” “Charcoal,” “Smoke”)</li><li>Takeout Packaging (containers, wraps, bags, cups)</li><li>Interior Visual Elements (neon signage, overall concept)</li><li>Print Collateral (menus, brochures, flyers)</li><li>Advertising Campaign</li><li>Tagline: *“Храна за [С]пoделяне” (“Food for Sharing/[Scrolling]”)</li><li>Social Media-inspired poster series</li><li>Vehicle Graphics for branded delivery</li><li>Social Media Visuals in multiple formats</li></ul>",
        technologies: ["Photoshop", "Illustrator"],
    },
    {
        id: 2,
        title: "Beer Brand “Peak”",
        category: "Branding",
        thumbnail: "./pictures/vruh-thumbnail.jpg",
        fullImage: "./pictures/vruh-full.jpg",
        resolutionPx: "4460x2186px",
        resolutionPpi: "150ppi",
        fileName: "branding_peak.psd",
        fileSize: "5.2MB",
        overview: "Връх (Bulgarian for “Peak”) is a conceptual beer brand that captures the spirit of nature, adventure, and handcrafted brewing. Designed with a rugged yet minimalistic aesthetic, this branding project aims to resonate with outdoorsy, quality-conscious consumers who value authenticity and visual storytelling. The project creates a unified identity across packaging, merchandise, and corporate stationery, elevating the brand into a lifestyle beyond beer.",
        conceptVisualLanguage: "The core concept is built around the motif of mountain exploration and Bulgarian natural landscapes, interpreted through a contemporary design lens. The custom logotype 'ВРЪХ' is stark and geometric, evoking stamped labels or alpine signage. A consistent mountain-scape illustration runs through all product variants, creating visual continuity across STOUT, CRAFT, and LAGER styles. The use of black, white, and muted natural tones—punctuated by bold accent colors (green, teal, amber)—represents the raw purity of ingredients and the elevation experience. The packaging and visuals exude calm strength, wild purity, and clean design, reflecting both the environment and product quality.",
        deliverablesIncluded: "<ul> <li>Logo & Visual Identity (featuring stylized “ВРЪХ” logotype)</li> <li>Custom Beer Bottle Labels (STOUT, CRAFT, LAGER—each with a unique accent color)</li> <li>Merchandise (T-shirts, pens, USB flash drive)</li> <li>Branded Stationery (letterhead, envelopes, business cards)</li> <li>Branded Takeaway Bag with mountain-pattern repeat</li> <li>Slogan: “Върховното изживяване!” ('The ultimate experience!')</li> </ul>",
        technologies: ["Photoshop", "Illustrator"],
        link: ""
    },
    {
        id: 3,
        title: "Wine Brand “Il Diavolo”",
        category: "Branding",
        thumbnail: "./pictures/diavolo-thumbnail.jpg",
        fullImage: "./pictures/diavolo-full.jpg",
        resolutionPx: "4763x2186px",
        resolutionPpi: "150ppi",
        fileName: "branding_ildiavolo.psd",
        fileSize: "5.2MB",
        overview: "il Diavolo is a bold and dramatic brand identity concept for a premium wine label and lifestyle product line. Rooted in a powerful mythological narrative and striking visual impact, the brand embodies intensity, temptation, and a rebellious sophistication. This project creates a cohesive identity system that appeals to thrill-seekers, design aficionados, and connoisseurs looking for more than just a drink—an experience.",
        conceptVisualLanguage: "The visual concept draws inspiration from infernal mythology and vintage ink illustration. A muscular devil figure holding a trident becomes the core brand character, illustrated in a fine, hand-drawn style with a modern twist. The logo features an expressive handwritten script for “Diavolo” with aggressive brushstroke accents and a red slash through the name—symbolizing danger, passion, and high energy. The overall color palette—white, deep black, and bold crimson red—evokes intensity, heat, and elegance. The branding balances traditional textures (grainy, hand-inked) with confident modern typography and layout.",
        deliverablesIncluded: "<ul> <li>Logo & Visual Identity (featuring illustrated devil and custom typography)</li> <li>Custom Wine Bottle Label (2018 Merlot with rich red & gray palette)</li> <li>Branded Stationery (letterhead, business cards, notebook)</li> <li>Merchandise (T-shirt, cap, tote bag, kraft paper gift bag)</li> <li>Slogan and subtitle in Italian—communicating mystique and origin</li> </ul>",
        technologies: ["Photoshop", "Illustrator"],
        link: ""
    },
    {
        id: 4,
        title: "Pizza Place “The Spot”",
        category: "Branding",
        thumbnail: "./pictures/pizzaspot-thumbnail.jpg",
        fullImage: "./pictures/pizzaspot-full.jpg",
        resolutionPx: "4988x2186px",
        resolutionPpi: "150ppi",
        fileName: "branding_thepspot.psd",
        fileSize: "5.2MB",
        overview: "The Spot is a fast-casual pizza brand that focuses on ultra-quick service (under 2 minutes!) and a fun, interactive customer experience. Designed to resonate with a young, dynamic, and social-media-savvy audience, the brand merges speed, flavor, and creativity into a bold visual identity that turns pizza time into playtime. The project creates a cheerful and cohesive brand presence across packaging, print, and marketing touchpoints.",
        conceptVisualLanguage: "The visual identity is centered around vibrant orange tones and playful, geometric patterns made of pizza slice icons. The logo combines a pizza slice with a map location pin—visually reinforcing the idea that this is the spot for quick, tasty food. The packaging uses game-inspired layouts (spinners, snake laderand ludo) to encourage interaction, humor, and repeat engagement. Typography is casual and energetic, while photography emphasizes hot, delicious slices in a circular “clock” motif to drive home the “ready in under 2 minutes” message. The visual tone is friendly, bold, and geared for high-impact in social environments.",
        deliverablesIncluded: "<ul> <li>Logo & Visual Identity (pizza/location hybrid mark)</li> <li>Branded Stationery (letterhead, business cards, envelopes, sticker)</li> <li>Custom Pizza Box Designs (game-style graphics for added entertainment)</li> <li>Advertising Posters & Flyers (with bold typography and sliced-pizza visuals)</li> <li>Slogan: “Пицата, която става за по-малко от 2 минути!” (“The pizza that’s ready in under 2 minutes!”)</li> <li>Social Media Handles and Ordering Details integrated into visuals</li> </ul>",
        technologies: ["Photoshop", "Illustrator"],
        link: ""
    },
    {
        id: 5,
        title: "CBD Brand “ERRA”",
        category: "Branding",
        thumbnail: "./pictures/erra-thumbnail.jpg",
        fullImage: "./pictures/erra-full.jpg",
        resolutionPx: "4203x2186px",
        resolutionPpi: "150ppi",
        fileName: "branding_erra.psd",
        fileSize: "5.2MB",
        overview: "Erra is a futuristic wellness and lifestyle brand that merges bold visual storytelling with the benefits of CBD and cannabis-derived products. Designed for a modern, edgy, and experience-driven audience, Erra infuses mystique, energy, and subcultural aesthetics into every product touchpoint. From CBD-infused drinks to curated hemp blends, the brand invites users to explore altered states of mind, focus, or relaxation—each product crafted with purpose, style, and attitude. The experience is not just therapeutic—it’s immersive, stylish, and unforgettable.",
        conceptVisualLanguage: "Erra’s visual identity leans into dark, smoky gradients illuminated by neon outlines and elemental icons. A unified system of bright, glowing colors distinguishes each product line—red for passion, yellow for energy, blue for mind-altering effects, and green for natural calm. Each product pouch and can is marked with glyph-like illustrations (skull, tree, heart, lightning bolt) to quickly communicate effect and vibe. Typography is sharp, modern, and futuristic, while packaging design incorporates cannabinoid breakdowns, effect icons, and interactive visual systems to create a ritualistic, collectible appeal. The tone is mysterious, loud, and designed for high impact in digital and retail spaces.",
        deliverablesIncluded: "<ul> <li>Logo & Visual Identity (cannabis + elemental mark system)</li> <li>CBD Beverage Cans (color-coded, 350ml, 25mg CBD each)</li> <li>CBD Hemp Oil Bottle (tinted dropper, clean labeling)</li> <li>Interactive Product Pouches (icon-based, effect-driven design with cannabinoid metrics)</li> <li>Custom Collector Box (magnet-lid, smoky interior, bold print)</li> <li>Website Link Integration & Digital-First Packaging (social-optimized visuals)</li> <li>Tagline / Vibe: “Beyond Calm. Beyond High. This is Erra.”</li> </ul>",
        technologies: ["Photoshop", "Illustrator"],
        link: ""
    },
];